schema_version = 1

[source]
repository = "https://github.com/johnny9/gui-qml.git"
reference = "https://github.com/johnny9/gui-qml/tree/v31"
fetch_ref = "refs/heads/v31"
commit = "25e056671840ce1ae1d6db6307d20d2b1f68e445"
bitcoin_commit = "dc282ff31d1cc97507530a541d9cec8a8f6a6ef4"
depends_patch = "patches/depends-Add-Qt-Qml-and-Qt-Quick-modules.patch"
depends_patch_sha256 = "6a8d4a8c3222c2fca258b5cd15eea7701a64c9ff4bfb9ecf2148a39949d03dd8"
patched_source_diff_sha256 = "710dd185d0d43b300703b5bd0154e07635d4472dd560e461d8d5788209003cb5"
patched_bitcoin_diff_sha256 = "17715ef316938e665f3107de5633c476ebfa1b4dcd6fe0c13e6b04ca1159b3bb"

[build]
build_type = "Release"
build_directory = "build-depends"
target = "bitcoin-core-app"
minimum_macos = "14.0"
architecture = "arm64"
display_version = "25e056671840"

[linux]
host = "x86_64-pc-linux-gnu"
architecture = "x86_64"
artifact_name = "bitcoin-core-app-signet-x86_64-linux-gnu"

[application]
bundle_name = "Bitcoin-QML"
display_name = "Bitcoin Core App Preview"
executable = "bitcoin-core-app"
bundle_identifier = "org.bitcoincore.gui-qml.preview"
volume_name = "Bitcoin QML Preview"
artifact_basename = "Bitcoin-QML-signet-arm64"
url_scheme = "bitcoin"
short_version = "31.0.0"
bundle_version = "31.0.0"

[[patches]]
path = "patches/0001-use-gui-qml-commit-for-version.patch"
target = "source"

[[patches]]
path = "patches/0002-default-to-signet.patch"
target = "bitcoin"
