schema_version = 1

[source]
repository = "https://github.com/johnny9/BitcoinCoreAppDevelopment.git"
reference = "https://github.com/johnny9/BitcoinCoreAppDevelopment/tree/qt6"
fetch_ref = "refs/heads/qt6"
commit = "d63e9642c2cfbb5ee1abad80688fbac89597b61a"
bitcoin_commit = "6574cb40869b96b9ffc79c19dc8f4e467d60f321"
depends_patch = "patches/depends-Add-Qt-Qml-and-Qt-Quick-modules.patch"
depends_patch_sha256 = "6a8d4a8c3222c2fca258b5cd15eea7701a64c9ff4bfb9ecf2148a39949d03dd8"
patched_source_diff_sha256 = "6348625431997ddddf364a1d127c8d54b569425158ecd0159ce4c756bab2d3e5"
patched_bitcoin_diff_sha256 = "366e20fc609045eae7f8e73fd2e185eac620d04d3a0eb662bb22b0f35bb8e884"

[build]
build_type = "Release"
build_directory = "build-depends"
target = "bitcoin-core-app"
minimum_macos = "14.0"
architecture = "arm64"
display_version = "d63e9642c2cf"

[application]
bundle_name = "Bitcoin-QML"
display_name = "Bitcoin Core App Preview"
executable = "bitcoin-core-app"
bundle_identifier = "org.bitcoincore.gui-qml.preview"
volume_name = "Bitcoin QML Preview"
artifact_basename = "Bitcoin-QML-signet-arm64"
url_scheme = "bitcoin"
short_version = "31.0.0"
bundle_version = "31.0.0"

[[patches]]
path = "patches/0001-use-gui-qml-commit-for-version.patch"
target = "source"

[[patches]]
path = "patches/0002-default-to-signet.patch"
target = "bitcoin"
